version: '3.7'

services:
  guidotools:
    build:
      context: .
    environment:
      AWS_S3_REGION_NAME: eu-west-1
      AWS_STORAGE_BUCKET_NAME: testing.antescofo.com
      AWS_ACCESS_KEY_ID: AKIAIAWTQU25LD76YBEA
      AWS_SECRET_ACCESS_KEY: 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
    volumes:
      - ./tools:/app/tools
      - ./platforms:/app/platforms
      - ./server:/app/server
      - ./lang:/app/lang
# docker-compose build && time docker-compose run --rm -v ~/Desktop/accomp.xml:/accomp.xml -v ~/Desktop/accomp.asco:/accomp.asco -v ~/Desktop/accomp.mp3:/accomp.mp3 guidotools videogen.sh /accomp.xml /accomp.asco /accomp.mp3 final_output.mp4


# Create a random accompanimement that is not generated yet
# docker-compose run -p 8080:8080 --rm guidotools generate_video

# Create a specific accompaniment
# docker-compose run -p 8080:8080 --rm guidotools generate_video ACCOM_PK
