site_name: The Guido Project
site_description: A guide to embed music notation.
copyright: Copyright &copy; 2019 <a href="http://www.grame.fr">Grame-CNCM</a>
nav:
    - Home: index.md
    - Guido API: 
      - 'API reference': dox/api/index.html
    - Internals: 
        - 'Global architecture': internals/architecture.md
        - 'The Abstract Representation': 
            - AR classes:  internals/arclasses.md
            - Tag Parameters:  internals/tagparams.md
        - 'The Graphic Representation': 
            - GR classes:  internals/grclasses.md
            - Layout steps:  internals/layout.md
        - 'The VGDevice layer': internals/vgdevice.md
        - 'Source code organisation': internals/src-code.md
        - 'Internals reference': dox/internal/index.html
    - Contributing: 
        - 'To do list': todo.md
        - 'Guidelines': https://github.com/grame-cncm/guidolib/wiki/Contributing

extra:
    social:
        - type: github
          link: https://github.com/grame-cncm/guidolib
        - type: home
          link: https://guidolib.grame.fr
        - type: envelope
          link: mailto:fober@grame.fr

plugins:
    - search
    - pdf-export:
          verbose: false
          media_type: print
          combined: true
          combined_output_path: GUidoEngine.pdf
          enabled_if_env: ENABLE_PDF_EXPORT

theme: united
#The available installed themes are: mkdocs, readthedocs, cinder, cosmo, flatly, spacelab, united, yeti 
 
extra_javascript:
#  - '/GMN/guidolib/libGUIDOEngine.js'
#  - '/GMN/guidolib/guidocode.js'
#  - '/BNF/railroad-diagrams/railroad-diagrams.js'

extra_css:
   - '/rsrc/guido.css'

markdown_extensions:
    - markdown_include.include:
        base_path: './docs'
