name: Docker

on: [push]

jobs:
  build:

    # Display name for the GHA page
    name: Linux docker

    runs-on: ubuntu-18.04

    timeout-minutes: 20

    steps:
    - name: Repo checkout
      uses: actions/checkout@v2

    - name: build
      run: |
        cd build/docker
        make all
